### ISSUE TITLE
Can't find TV

### ISSUE THREAD

**Issue by WeeJeWel** [athombv/com.lg.webos#1]
I cannot seem to isolate the issue. My hypothesis is that LG updated their software recently.

**Comment by philsniff** [comment]
any news @WeeJeWel? i can see that you modified some files two days ago. should my tv with the 0.10 version be available?

greeds

**Comment by WeeJeWel** [comment]
Hm my own TV can be found since, well, a long time ago. What's your WebOS version?

**Comment by philsniff** [comment]
i think version number something with 5.05. and a LG 55lb630v (2014). is not webOS 2 i think, i can make a snapshot of my tv-setting later if it could help you.

**Comment by WeeJeWel** [comment]
I think webOS 2 is required for the library I'm using. Maybe this one works? https://apps.athom.com/app/com.lg.smarttv

**Comment by philsniff** [comment]
hehe, no. i tested it also. 
i will then go futher with ir. works at the moment. 

thanks ;-)

**Comment by philsniff** [comment]
hey @WeeJeWel suddently since homey firmware 1.0.5 the app finds my 2014 LG with webos != 2!!
great! only some minor bugs now. but therefore i will open a new issue (app crashes and must be disable/enable again)

but what is the reason? ah, ok, yesterday there was an update from lg, so it could be the small update and not homey 1.0.5.

**Comment by bvdbos** [comment]
close me :+1:
